name: Dependency Management

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  push:
    branches: [ main, master ]
    paths:
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high

  govulncheck:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

  outdated:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install go-mod-outdated
        run: go install github.com/psampaz/go-mod-outdated@latest

      - name: Check for outdated dependencies
        run: |
          go list -u -m -json all | go-mod-outdated -update -direct